-- -----------------------------------------------------
-- Insert data for cards table
-- Run this SQL to populate the cards table
-- -----------------------------------------------------

INSERT INTO uno.cards (card_id,description,image_adress) 
  VALUES
(1,'Red 0','/images/red0.jpg'),
(2,'Red 1','/images/red1.jpg'),
(3,'Red 2','/images/red2.jpg'),
(4,'Red 3','/images/red3.jpg'),
(5,'Red 4','/images/red4.jpg'),
(6,'Red 5','/images/red5.jpg'),
(7,'Red 6','/images/red6.jpg'),
(8,'Red 7','/images/red7.jpg'),
(9,'Red 8','/images/red8.jpg'),
(10,'Red 9','/images/red9.jpg'),
(11,'Red 1','/images/red1.jpg'),
(12,'Red 2','/images/red2.jpg'),
(13,'Red 3','/images/red3.jpg'),
(14,'Red 4','/images/red4.jpg'),
(15,'Red 5','/images/red5.jpg'),
(16,'Red 6','/images/red6.jpg'),
(17,'Red 7','/images/red7.jpg'),
(18,'Red 8','/images/red8.jpg'),
(19,'Red 9','/images/red9.jpg'),
(20,'Green 0','/images/green0.jpg'),
(21,'Green 1','/images/green1.jpg'),
(22,'Green 2','/images/green2.jpg'),
(23,'Green 3','/images/green3.jpg'),
(24,'Green 4','/images/green4.jpg'),
(25,'Green 5','/images/green5.jpg'),
(26,'Green 6','/images/green6.jpg'),
(27,'Green 7','/images/green7.jpg'),
(28,'Green 8','/images/green8.jpg'),
(29,'Green 1','/images/green1.jpg'),
(30,'Green 2','/images/green2.jpg'),
(31,'Green 3','/images/green3.jpg'),
(32,'Green 4','/images/green4.jpg'),
(33,'Green 5','/images/green5.jpg'),
(34,'Green 6','/images/green6.jpg'),
(35,'Green 7','/images/green7.jpg'),
(36,'Green 8','/images/green8.jpg'),
(37,'Green 9','/images/green9.jpg'),
(38,'Green 9','/images/green9.jpg'),
(39,'Yellow 0','/images/yellow0.jpg'),
(40,'Yellow 1','/images/yellow1.jpg'),
(41,'Yellow 2','/images/yellow2.jpg'),
(42,'Yellow 3','/images/yellow3.jpg'),
(43,'Yellow 4','/images/yellow4.jpg'),
(44,'Yellow 5','/images/yellow5.jpg'),
(45,'Yellow 6','/images/yellow6.jpg'),
(46,'Yellow 7','/images/yellow7.jpg'),
(47,'Yellow 8','/images/yellow8.jpg'),
(48,'Yellow 9','/images/yellow9.jpg'),
(49,'Yellow 1','/images/yellow1.jpg'),
(50,'Yellow 2','/images/yellow2.jpg'),
(51,'Yellow 3','/images/yellow3.jpg'),
(52,'Yellow 4','/images/yellow4.jpg'),
(53,'Yellow 5','/images/yellow5.jpg'),
(54,'Yellow 6','/images/yellow6.jpg'),
(55,'Yellow 7','/images/yellow7.jpg'),
(56,'Yellow 8','/images/yellow8.jpg'),
(57,'Yellow 9','/images/yellow9.jpg'),
(58,'Blue 0','/images/blue0.jpg'),
(59,'Blue 1','/images/blue1.jpg'),
(60,'Blue 2','/images/blue2.jpg'),
(61,'Blue 3','/images/blue3.jpg'),
(62,'Blue 4','/images/blue4.jpg'),
(63,'Blue 5','/images/blue5.jpg'),
(64,'Blue 6','/images/blue6.jpg'),
(65,'Blue 7','/images/blue7.jpg'),
(66,'Blue 8','/images/blue8.jpg'),
(67,'Blue 9','/images/blue9.jpg'),
(68,'Blue 1','/images/blue1.jpg'),
(69,'Blue 2','/images/blue2.jpg'),
(70,'Blue 3','/images/blue3.jpg'),
(71,'Blue 4','/images/blue4.jpg'),
(72,'Blue 5','/images/blue5.jpg'),
(73,'Blue 6','/images/blue6.jpg'),
(74,'Blue 7','/images/blue7.jpg'),
(75,'Blue 8','/images/blue8.jpg'),
(76,'Blue 9','/images/blue9.jpg'),
(77,'Red draw two','/images/red_draw_two.jpg'),
(78,'Red draw two','/images/red_draw_two.jpg'),
(79,'Green draw two','/images/green_draw_two.jpg'),
(80,'Green draw two','/images/green_draw_two.jpg'),
(81,'Yellow draw two','/images/yellow_draw_two.jpg'),
(82,'Yellow draw two','/images/yellow_draw_two.jpg'),
(83,'Blue draw two','/images/blue_draw_two.jpg'),
(84,'Blue draw two','/images/blue_draw_two.jpg'),
(85,'Red skip','/images/red_skip.jpg'),
(86,'Red skip','/images/red_skip.jpg'),
(87,'Green skip','/images/green_skip.jpg'),
(88,'Green skip','/images/green_skip.jpg'),
(89,'Yellow skip','/images/yellow_skip.jpg'),
(90,'Yellow skip','/images/yellow_skip.jpg'),
(91,'Blue skip','/images/blue_skip.jpg'),
(92,'Blue skip','/images/blue_skip.jpg'),
(93,'Red reverse','/images/red_reverse.jpg'),
(94,'Red reverse','/images/red_reverse.jpg'),
(95,'Green reverse','/images/green_reverse.jpg'),
(96,'Green reverse','/images/green_reverse.jpg'),
(97,'Yellow reverse','/images/yellow_reverse.jpg'),
(98,'Yellow reverse','/images/yellow_reverse.jpg'),
(99,'Blue reverse','/images/blue_reverse.jpg'),
(100,'Blue reverse','/images/blue_reverse.jpg'),
(101,'Wild','/images/wild.jpg'),
(102,'Wild','/images/wild.jpg'),
(103,'Wild','/images/wild.jpg'),
(104,'Wild','/images/wild.jpg'),
(105,'Wild draw four','/images/wild_draw_four.jpg'),
(106,'Wild draw four','/images/wild_draw_four.jpg'),
(107,'Wild draw four','/images/wild_draw_four.jpg'),
(108,'Wild draw four','/images/wild_draw_four.jpg');