-- -----------------------------------------------------
-- Insert data for cards table
-- Run this SQL to populate the cards table
-- -----------------------------------------------------

INSERT INTO uno.cards (card_id,description,image_adress) 
  VALUES
(1,'Red 0','/images/red0.jpg'),
(2,'Red 1','/images/red1.jpg'),
(3,'Red 2','/images/red2.jpg'),
(4,'Red 3','/images/red3.jpg'),
(5,'Red 4','/images/red4.jpg'),
(6,'Red 5','/images/red5.jpg'),
(7,'Red 6','/images/red6.jpg'),
(8,'Red 7','/images/red7.jpg'),
(9,'Red 8','/images/red8.jpg'),
(10,'Red 9','/images/red9.jpg'),
(11,'Red 1','/images/red1.jpg'),
(12,'Red 2','/images/red2.jpg'),
(13,'Red 3','/images/red3.jpg'),
(14,'Red 4','/images/red4.jpg'),
(15,'Red 5','/images/red5.jpg'),
(16,'Red 6','/images/red6.jpg'),
(17,'Red 7','/images/red7.jpg'),
(18,'Red 8','/images/red8.jpg'),
(19,'Red 9','/images/red9.jpg'),
(20,'Red draw two','/images/red_draw_two.jpg'),
(21,'Red draw two','/images/red_draw_two.jpg'),
(22,'Red skip','/images/red_skip.jpg'),
(23,'Red skip','/images/red_skip.jpg'),
(24,'Red reverse','/images/red_reverse.jpg'),
(25,'Red reverse','/images/red_reverse.jpg'),

(26,'Green 0','/images/green0.jpg'),
(27,'Green 1','/images/green1.jpg'),
(28,'Green 2','/images/green2.jpg'),
(29,'Green 3','/images/green3.jpg'),
(30,'Green 4','/images/green4.jpg'),
(31,'Green 5','/images/green5.jpg'),
(32,'Green 6','/images/green6.jpg'),
(33,'Green 7','/images/green7.jpg'),
(34,'Green 8','/images/green8.jpg'),
(35,'Green 1','/images/green1.jpg'),
(36,'Green 2','/images/green2.jpg'),
(37,'Green 3','/images/green3.jpg'),
(38,'Green 4','/images/green4.jpg'),
(39,'Green 5','/images/green5.jpg'),
(40,'Green 6','/images/green6.jpg'),
(41,'Green 7','/images/green7.jpg'),
(42,'Green 8','/images/green8.jpg'),
(43,'Green 9','/images/green9.jpg'),
(44,'Green 9','/images/green9.jpg'),
(45,'Green draw two','/images/green_draw_two.jpg'),
(46,'Green draw two','/images/green_draw_two.jpg'),
(47,'Green skip','/images/green_skip.jpg'),
(48,'Green skip','/images/green_skip.jpg'),
(49,'Green reverse','/images/green_reverse.jpg'),
(50,'Green reverse','/images/green_reverse.jpg'),

(51,'Yellow 0','/images/yellow0.jpg'),
(52,'Yellow 1','/images/yellow1.jpg'),
(53,'Yellow 2','/images/yellow2.jpg'),
(54,'Yellow 3','/images/yellow3.jpg'),
(55,'Yellow 4','/images/yellow4.jpg'),
(56,'Yellow 5','/images/yellow5.jpg'),
(57,'Yellow 6','/images/yellow6.jpg'),
(58,'Yellow 7','/images/yellow7.jpg'),
(59,'Yellow 8','/images/yellow8.jpg'),
(60,'Yellow 9','/images/yellow9.jpg'),
(61,'Yellow 1','/images/yellow1.jpg'),
(62,'Yellow 2','/images/yellow2.jpg'),
(63,'Yellow 3','/images/yellow3.jpg'),
(64,'Yellow 4','/images/yellow4.jpg'),
(65,'Yellow 5','/images/yellow5.jpg'),
(66,'Yellow 6','/images/yellow6.jpg'),
(67,'Yellow 7','/images/yellow7.jpg'),
(68,'Yellow 8','/images/yellow8.jpg'),
(69,'Yellow 9','/images/yellow9.jpg'),
(70,'Yellow draw two','/images/yellow_draw_two.jpg'),
(71,'Yellow draw two','/images/yellow_draw_two.jpg'),
(72,'Yellow skip','/images/yellow_skip.jpg'),
(73,'Yellow skip','/images/yellow_skip.jpg'),
(74,'Yellow reverse','/images/yellow_reverse.jpg'),
(75,'Yellow reverse','/images/yellow_reverse.jpg'),

(76,'Blue 0','/images/blue0.jpg'),
(77,'Blue 1','/images/blue1.jpg'),
(78,'Blue 2','/images/blue2.jpg'),
(79,'Blue 3','/images/blue3.jpg'),
(80,'Blue 4','/images/blue4.jpg'),
(81,'Blue 5','/images/blue5.jpg'),
(82,'Blue 6','/images/blue6.jpg'),
(83,'Blue 7','/images/blue7.jpg'),
(84,'Blue 8','/images/blue8.jpg'),
(85,'Blue 9','/images/blue9.jpg'),
(86,'Blue 1','/images/blue1.jpg'),
(87,'Blue 2','/images/blue2.jpg'),
(88,'Blue 3','/images/blue3.jpg'),
(89,'Blue 4','/images/blue4.jpg'),
(90,'Blue 5','/images/blue5.jpg'),
(91,'Blue 6','/images/blue6.jpg'),
(92,'Blue 7','/images/blue7.jpg'),
(93,'Blue 8','/images/blue8.jpg'),
(94,'Blue 9','/images/blue9.jpg'),
(95,'Blue draw two','/images/blue_draw_two.jpg'),
(96,'Blue draw two','/images/blue_draw_two.jpg'),
(97,'Blue skip','/images/blue_skip.jpg'),
(98,'Blue skip','/images/blue_skip.jpg'),
(99,'Blue reverse','/images/blue_reverse.jpg'),
(100,'Blue reverse','/images/blue_reverse.jpg'),

(101,'Wild','/images/wild.jpg'),
(102,'Wild','/images/wild.jpg'),
(103,'Wild','/images/wild.jpg'),
(104,'Wild','/images/wild.jpg'),
(105,'Wild draw four','/images/wild_draw_four.jpg'),
(106,'Wild draw four','/images/wild_draw_four.jpg'),
(107,'Wild draw four','/images/wild_draw_four.jpg'),
(108,'Wild draw four','/images/wild_draw_four.jpg');