-- -----------------------------------------------------
-- Insert data for cards table
-- Run this SQL to populate the cards table
-- -----------------------------------------------------

INSERT INTO cards (card_id,description,face,color,value,image_address) 
  VALUES
(1,'red 1','1','red','1','/images/red1.jpg'),
(2,'red 2','2','red','2','/images/red2.jpg'),
(3,'red 3','3','red','3','/images/red3.jpg'),
(4,'red 4','4','red','4','/images/red4.jpg'),
(5,'red 5','5','red','5','/images/red5.jpg'),
(6,'red 6','6','red','6','/images/red6.jpg'),
(7,'red 7','7','red','7','/images/red7.jpg'),
(8,'red 8','8','red','8','/images/red8.jpg'),
(9,'red 9','9','red','9','/images/red9.jpg'),
(10,'red 0','0','red','0','/images/red0.jpg'),
(11,'red 1','1','red','1','/images/red1.jpg'),
(12,'red 2','2','red','2','/images/red2.jpg'),
(13,'red 3','3','red','3','/images/red3.jpg'),
(14,'red 4','4','red','4','/images/red4.jpg'),
(15,'red 5','5','red','5','/images/red5.jpg'),
(16,'red 6','6','red','6','/images/red6.jpg'),
(17,'red 7','7','red','7','/images/red7.jpg'),
(18,'red 8','8','red','8','/images/red8.jpg'),
(19,'red 9','9','red','9','/images/red9.jpg'),

(20,'red draw two','draw two','red','20','/images/red_draw_two.jpg'),
(21,'red draw two','draw two','red','20','/images/red_draw_two.jpg'),
(22,'red skip','skip','red','20','/images/red_skip.jpg'),
(23,'red skip','skip','red','20','/images/red_skip.jpg'),
(24,'red reverse','reverse','red','20','/images/red_reverse.jpg'),
(25,'red reverse','reverse','red','20','/images/red_reverse.jpg'),

(26,'green 1','1','green','1','/images/green1.jpg'),
(27,'green 2','2','green','2','/images/green2.jpg'),
(28,'green 3','3','green','3','/images/green3.jpg'),
(29,'green 4','4','green','4','/images/green4.jpg'),
(30,'green 5','5','green','5','/images/green5.jpg'),
(31,'green 6','6','green','6','/images/green6.jpg'),
(32,'green 7','7','green','7','/images/green7.jpg'),
(33,'green 8','8','green','8','/images/green8.jpg'),
(34,'green 9','9','green','9','/images/green9.jpg'),
(35,'green 0','0','green','0','/images/green0.jpg'),
(36,'green 1','1','green','1','/images/green1.jpg'),
(37,'green 2','2','green','2','/images/green2.jpg'),
(38,'green 3','3','green','3','/images/green3.jpg'),
(39,'green 4','4','green','4','/images/green4.jpg'),
(40,'green 5','5','green','5','/images/green5.jpg'),
(41,'green 6','6','green','6','/images/green6.jpg'),
(42,'green 7','7','green','7','/images/green7.jpg'),
(43,'green 8','8','green','8','/images/green8.jpg'),
(44,'green 9','9','green','9','/images/green9.jpg'),

(45,'green draw two','draw two','green','20','/images/green_draw_two.jpg'),
(46,'green draw two','draw two','green','20','/images/green_draw_two.jpg'),
(47,'green skip','skip','green','20','/images/green_skip.jpg'),
(48,'green skip','skip','green','20','/images/green_skip.jpg'),
(49,'green reverse','reverse','green','20','/images/green_reverse.jpg'),
(50,'green reverse','reverse','green','20','/images/green_reverse.jpg'),

(51,'yellow 1','1','yellow','1','/images/yellow1.jpg'),
(52,'yellow 2','2','yellow','2','/images/yellow2.jpg'),
(53,'yellow 3','3','yellow','3','/images/yellow3.jpg'),
(54,'yellow 4','4','yellow','4','/images/yellow4.jpg'),
(55,'yellow 5','5','yellow','5','/images/yellow5.jpg'),
(56,'yellow 6','6','yellow','6','/images/yellow6.jpg'),
(57,'yellow 7','7','yellow','7','/images/yellow7.jpg'),
(58,'yellow 8','8','yellow','8','/images/yellow8.jpg'),
(59,'yellow 9','9','yellow','9','/images/yellow9.jpg'),
(60,'yellow 0','0','yellow','0','/images/yellow0.jpg'),
(61,'yellow 1','1','yellow','1','/images/yellow1.jpg'),
(62,'yellow 2','2','yellow','2','/images/yellow2.jpg'),
(63,'yellow 3','3','yellow','3','/images/yellow3.jpg'),
(64,'yellow 4','4','yellow','4','/images/yellow4.jpg'),
(65,'yellow 5','5','yellow','5','/images/yellow5.jpg'),
(66,'yellow 6','6','yellow','6','/images/yellow6.jpg'),
(67,'yellow 7','7','yellow','7','/images/yellow7.jpg'),
(68,'yellow 8','8','yellow','8','/images/yellow8.jpg'),
(69,'yellow 9','9','yellow','9','/images/yellow9.jpg'),

(70,'yellow draw two','draw two','yellow','20','/images/yellow_draw_two.jpg'),
(71,'yellow draw two','draw two','yellow','20','/images/yellow_draw_two.jpg'),
(72,'yellow skip','skip','yellow','20','/images/yellow_skip.jpg'),
(73,'yellow skip','skip','yellow','20','/images/yellow_skip.jpg'),
(74,'yellow reverse','reverse','yellow','20','/images/yellow_reverse.jpg'),
(75,'yellow reverse','reverse','yellow','20','/images/yellow_reverse.jpg'),

(76,'blue 1','1','blue','1','/images/blue1.jpg'),
(77,'blue 2','2','blue','2','/images/blue2.jpg'),
(78,'blue 3','3','blue','3','/images/blue3.jpg'),
(79,'blue 4','4','blue','4','/images/blue4.jpg'),
(80,'blue 5','5','blue','5','/images/blue5.jpg'),
(81,'blue 6','6','blue','6','/images/blue6.jpg'),
(82,'blue 7','7','blue','7','/images/blue7.jpg'),
(83,'blue 8','8','blue','8','/images/blue8.jpg'),
(84,'blue 9','9','blue','9','/images/blue9.jpg'),
(85,'blue 0','0','blue','0','/images/blue0.jpg'),
(86,'blue 1','1','blue','1','/images/blue1.jpg'),
(87,'blue 2','2','blue','2','/images/blue2.jpg'),
(88,'blue 3','3','blue','3','/images/blue3.jpg'),
(89,'blue 4','4','blue','4','/images/blue4.jpg'),
(90,'blue 5','5','blue','5','/images/blue5.jpg'),
(91,'blue 6','6','blue','6','/images/blue6.jpg'),
(92,'blue 7','7','blue','7','/images/blue7.jpg'),
(93,'blue 8','8','blue','8','/images/blue8.jpg'),
(94,'blue 9','9','blue','9','/images/blue9.jpg'),

(95,'blue draw two','draw two','blue','20','/images/blue_draw_two.jpg'),
(96,'blue draw two','draw two','blue','20','/images/blue_draw_two.jpg'),
(97,'blue skip','skip','blue','20','/images/blue_skip.jpg'),
(98,'blue skip','skip','blue','20','/images/blue_skip.jpg'),
(99,'blue reverse','reverse','blue','20','/images/blue_reverse.jpg'),
(100,'blue reverse','reverse','blue','20','/images/blue_reverse.jpg'),

(101,'wild','wild','black',50,'/images/wild.jpg'),
(102,'wild','wild','black',50,'/images/wild.jpg'),
(103,'wild','wild','black',50,'/images/wild.jpg'),
(104,'wild','wild','black',50,'/images/wild.jpg'),

(105,'wild draw four','wild draw four','black',50,'/images/wild_draw_four.jpg'),
(106,'wild draw four','wild draw four','black',50,'/images/wild_draw_four.jpg'),
(107,'wild draw four','wild draw four','black',50,'/images/wild_draw_four.jpg'),
(108,'wild draw four','wild draw four','black',50,'/images/wild_draw_four.jpg'),